#Test with: http://editor.swagger.io/

swagger: '2.0'
info:
  version: 1.0.0
  title: Microservice for Wallet
  description: Java + MySQL
  license:
    name: 2F Group
host: 192.168.99.101:4040
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /wallets/resources/wallet/{id}:
    get:
      summary: Returns a wallet with the given id
      operationId: getWalletById
      parameters:
        - name: id
          in: path
          description: The id of the wallet to be returned
          required: true
          type: integer
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Wallet'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorModel'
        '406':
            description: Not Acceptable (Invalid Params)
            schema:
              $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
    put:
      summary: Updates a wallet with the given id
      operationId: updateWallet
      parameters:
        - name: id
          in: path
          description: The id of the wallet to be updated
          required: true
          type: integer
        - name: balance
          in: body
          required: true
          description: Wallet Object
          schema:
            $ref: '#/definitions/WalletInput'
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorModel'
        '406':
            description: Not Acceptable (Invalid Params)
            schema:
              $ref: '#/definitions/ErrorModel'
        '500':
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorModel'
   

definitions:

  # Wallet
  Wallet:
    type: object
    properties:
      id:
        type: integer
      balance:
        type: Long
      
  WalletInput:
    type: object
    properties:
      balance:
        type: Long
      
# Errors
  ErrorModel:
    type: object
    required:
      - message
      - code
    properties:
      message:
        type: string
      code:
        type: number
      description:
        type: object